# Generated by Django 4.1.2 on 2022-10-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(max_length=50)),
                ('name_last', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('bpt_confidence', models.FloatField()),
                ('bpt_delegator', models.FloatField()),
                ('bpt_determination', models.FloatField()),
                ('bpt_disruptor', models.FloatField()),
                ('bpt_independence', models.FloatField()),
                ('bpt_knowledge', models.FloatField()),
                ('bpt_profitability', models.FloatField()),
                ('bpt_relationship', models.FloatField()),
                ('bpt_risk', models.FloatField()),
                ('bpt_selling', models.FloatField()),
            ],
        ),
    ]
