# Generated by Django 4.1.2 on 2022-11-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requestedteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reqID', models.IntegerField()),
                ('team', models.TextField()),
            ],
        ),
    ]
